# Generated by Django 2.1.3 on 2019-03-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0013_auto_20181209_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='value_phone',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
